-- ============================================================
-- CuVR Physio — automated SOAP notes
--
-- One SOAP note per completed session, generated by the AI service
-- right after the session ends. The physio can review and (later)
-- edit before signing off; we keep the AI's original draft and the
-- physio's edits in separate columns so we always have an audit trail.
-- ============================================================

create table if not exists public.soap_notes (
  id              uuid        primary key default gen_random_uuid(),
  session_id      uuid        not null unique references public.sessions(id) on delete cascade,
  patient_id      uuid        not null references public.patients(id) on delete cascade,
  physio_id       uuid        references public.profiles(id) on delete set null,
  generated_at    timestamptz not null default now(),
  edited_at       timestamptz,
  signed_at       timestamptz,                  -- physio confirms the note is final
  -- AI-generated content; never overwritten
  content         jsonb       not null,         -- { subjective, objective, assessment, plan }
  -- Physio's manual edits, kept separate from the AI draft
  edited_content  jsonb,
  features        jsonb       not null default '{}'::jsonb,
  source          text        not null default 'ai' check (source in ('ai','rule_fallback'))
);

create index if not exists idx_soap_notes_patient    on public.soap_notes(patient_id);
create index if not exists idx_soap_notes_generated  on public.soap_notes(generated_at desc);

alter table public.soap_notes enable row level security;

create policy "physio reads own soap notes" on public.soap_notes for select
  using (
    exists (
      select 1 from public.patients p
      where p.id = soap_notes.patient_id
        and p.physio_id = auth.uid()
    )
  );

create policy "physio updates own soap notes" on public.soap_notes for update
  using (
    exists (
      select 1 from public.patients p
      where p.id = soap_notes.patient_id
        and p.physio_id = auth.uid()
    )
  );

notify pgrst, 'reload schema';
